spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:appdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true # DB ??? ?? ?? ? ???? ??? ?? ??? ?? ?????? ??? ``?? ?? ???.
    open-in-view: false
    show-sql: true
    database: h2
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: this-is-a-very-long-secret-for-dev-only-change-in-prod-1234567890
  access-token-validity-ms: 3600000 # 1h

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
